### ISSUE TITLE
textrange of spans are incorrect

### ISSUE THREAD

**Issue by AurelienMassiot** [paperai/pdfanno#118]
It seems that the textrange returned in the annotation file is incorrect, when you compare it to the textrange of the pdftxt file.

For example, if I have the a span "Syntatic parsing", in the annotation file its textrange is [1313,1328], but in the pdftxt file it is [1533-1549] (which seems correct).

Thanks for your work !

**Comment by hshindo** [comment]
Thanks for the report.
I'll look into the details.

**Comment by hshindo** [comment]
It seems [1313,1328] is a line number without blank lines.
I don't think the blank line should be counted.
But it's possible to add an ID (the first column) without blank lines as follows, which should match with textrange.
```
1	1	TEXT	P	106.4301	754.63226	5.478471	10.705882
2	1	TEXT	r	111.90857	754.63226	3.4879298	10.705882
3	1	TEXT	o	114.99301	754.63226	4.4832	10.705882
4	1	TEXT	c	119.47621	754.63226	3.981082	10.705882
5	1	TEXT	e	123.45729	754.63226	3.981082	10.705882
6	1	TEXT	e	127.43837	754.63226	3.981082	10.705882
7	1	TEXT	d	131.41945	754.63226	4.4832	10.705882
8	1	TEXT	i	135.90265	754.63226	2.4926593	10.705882
9	1	TEXT	n	138.39531	754.63226	4.4832	10.705882
10	1	TEXT	g	142.87851	754.63226	4.4832	10.705882
11	1	TEXT	s	147.36171	754.63226	3.4879298	10.705882

12	1	TEXT	o	153.09125	754.63226	4.4832	10.705882
13	1	TEXT	f	157.57445	754.63226	2.4926593	10.705882

14	1	TEXT	t	162.30872	754.63226	2.4926593	10.705882
15	1	TEXT	h	164.80138	754.63226	4.4832	10.705882
16	1	TEXT	e	169.28458	754.63226	3.981082	10.705882
```

**Comment by AurelienMassiot** [comment]
Yes, the ID would be a good idea. Could you add it so that we have it when you download the pdftxt file ?

Thanks for your quick answer anyway.

**Comment by hshindo** [comment]
I got it.

**Comment by hshindo** [comment]
Updated.
https://paperai.github.io/pdfanno/latest/

**Comment by AurelienMassiot** [comment]
What has changed ? I don't see any difference.  
I think, there should be two textranges : the current one and the one when you count blankspaces (so, blankspaces should be letters too), for example : 

```
1 1 TEXT o
2 2 TEXT f
   3 TEXT  
3 4 TEXT t
4 5 TEXT h
5 6 TEXT e
```

The first textrange, you don't count blankspaces, the second texrange, you count textrange as a letter

**Comment by hshindo** [comment]
we shouldn't count the blankspaces because pdf doesn't contain whitespaces. 
The blank line is automatically inserted by simple heuristic rules, thus it might include errors.

**Comment by AurelienMassiot** [comment]
Alright, as you wish.
