### ISSUE TITLE
Highlighting and Data text retreival not working

### ISSUE THREAD

**Issue by Deamoner** [paperai/pdfanno#184]
I just tested out your demo on my own pdf. The highlight seems to have some static lines it can follow which was inbetween my line seperation. In addition the text that is highlight is not the text that shows up in the annontation download. Essentially making this product not function in a useable way. I can send along my pdf and annontation file to demostrate.

**Comment by hshindo** [comment]
Please share your sample pdf and .pdfanno file.

**Comment by Deamoner** [comment]
[WV15825 Complete CSR Redacted.pdf](https://github.com/paperai/pdfanno/files/2223817/WV15825.Complete.CSR.Redacted.pdf)

**Comment by Deamoner** [comment]
sorry the annon file is being blocking from upload. Here is the text: 

version = "0.4.0"
pdfextract-version = "0.2.4"

[1]
type = "span"
page = 1
label = "span1"
text = "on Grammars (SR-TSGs)"
textrange = [577,595]

[2]
type = "span"
page = 1
label = "span1"
text = "an extension of th"
textrange = [627,641]

[3]
type = "span"
page = 1
label = "span1"
text = "use symbol reﬁnement t"
textrange = [3047,3065]

[4]
type = "span"
page = 1
label = "span1"
text = "utomatic and consist"
textrange = [830,847]

[5]
type = "span"
page = 1
label = ""
text = "tly such as pred"
textrange = [2239,2251]

[6]
type = "relation"
dir = "one-way"
ids = [5,4]
label = "relation1"

[7]
type = "span"
page = 1
label = ""
text = "Collins, 2003; Matsuzaki et al., 2005). Symbol reﬁnement is a succe"
textrange = [3089,3145]

[8]
type = "span"
page = 1
label = "tester1"
text = "angil and Shieber, 2010)"
textrange = [1548,1568]

**Comment by hshindo** [comment]
> In addition the text that is highlight is not the text that shows up in the annontation download.

For your sample anno above, here is the pdf.txt.
From `577` to `595`, the text is `on Grammars (SR-TSGs)`.

![image](https://user-images.githubusercontent.com/6833527/43282803-1eff8a98-9152-11e8-997a-fa875e07e56d.png)
