### ISSUE TITLE
pdfextract-0.2.4.jar is missing

### ISSUE THREAD

**Issue by aleyan** [paperai/pdfanno#185]
package.json specifies that `pdfextract-0.2.4.jar` should be downloaded from `https://github.com/paperai/pdfextract/releases/download/untagged-6b0e4f23df695e8b7587/pdfextract-0.2.4.jar` however that link 404s. If you don't already have `pdfextract-0.2.4.jar` then github's 404 error html page gets saved as the `pdfextract-0.2.4.jar` and processing fails.

**Comment by hshindo** [comment]
Good point.
Please download the following (rename .zip to .jar).
[pdfextract-0.2.4.zip](https://github.com/paperai/pdfanno/files/2240104/pdfextract-0.2.4.zip)

**Comment by hshindo** [comment]
Thanks for your report.
Fixed the link.

**Comment by aleyan** [comment]
The link to the jar in package.json should also point to the new location at `https://github.com/paperai/pdfextract/releases/download/v0.2.4/pdfextract-0.2.4.jar`.

Thank you for quick response.

**Comment by aleyan** [comment]
Created #186 to fix the url.
