### ISSUE TITLE
pdf-sample.pdf.0-3-0.txt.gz what is this for?

### ISSUE THREAD

**Issue by Joozty** [paperai/pdfanno#191]
Hi, 

I am trying to set up your project on local environment but I've got some problems when I want to load my own .pdf file. It seems every pdf file must have .txt.gz version. What is this for? Can I disable it somehow?

```
Failed to analyze the PDF.
Reason: Error: HTTP 404 - pdftxtファイルのロードに失敗しました。
```

Thanks

**Comment by hshindo** [comment]
Are you using the latest master?

pdfanno requires `pdf.txt` file, which is generated by [pdfextract](https://github.com/paperai/pdfextract).
`pdf.txt.gz` is just an compressed file of `pdf.txt`.
For our demo, the file is generated on our server and loaded by pdfanno.

To generate `pdf.txt.gz` manually, download pdfextract.jar, put it in your local directory with pdf files, then double-click the pdfextract.jar. pdfextract generates `pdf.txt.gz` files for every pdf files.
`0-3-0` is a pdfextract-version. If you need `0-3-0`, use pdfextract-0.3.0.jar.
Please see [package.json](https://github.com/paperai/pdfanno/blob/c8c459b2829aa00a68fda744e942aa3e914d1ef0/package.json#L26) for pdfanno-pdfextract correspondence.

**Comment by Joozty** [comment]
Thanks for the quick and prompt response. If I understand it correctly it won't work without a .txt version, will it?

**Comment by hshindo** [comment]
No, it won't work without .txt file.
The annotation file (.pdfanno) and .txt file are dependent each other.

**Comment by Joozty** [comment]
One more question. How is then possible that [`pdf`](https://paperai.github.io/pdfanno/latest/?pdf=http://www.aclweb.org/anthology/P12-1046.pdf) get param works? Is .txt generated on fly? My point is that I have a lot of pdfs and cannot generate txt version for every file because of space. Would it be possible to call just some js function that will do pretty much it?

**Comment by hshindo** [comment]
The URL param is sent to our server, then the server download the pdf and runs pdfextract.jar.
If you build a server with java environment, you can do exactly the same as our demo.
(local server is also fine.)

Until [version 0.4.1](https://github.com/paperai/pdfanno/tree/v0.4.1), the pdfanno repo contains server's implementation to handle such cases.
Please take a look at [`server/`](https://github.com/paperai/pdfanno/tree/v0.4.1/server).

**Comment by Joozty** [comment]
@hshindo Thanks a lot for the clarification. :) I am closing it now and btw. great project.
