### ISSUE TITLE
Presentation mode arrows don't work

### ISSUE THREAD

**Issue by Joozty** [paperai/pdfanno#192]
Hi, I am running in an issue where left/right arrows don't work. Did you disable it on purpose or where can be a problem? I thought it is in [pdf.js](https://github.com/mozilla/pdf.js) library on default.

Thanks

**Comment by hshindo** [comment]
Which left/right arrows are you referring to?

**Comment by Joozty** [comment]
Sorry, I forgot to mention where. It is in presentation mode. 

![screen shot 2018-09-18 at 10](https://user-images.githubusercontent.com/12775440/45678613-bdae3300-bb2e-11e8-9261-58a4ef756fc4.png)
