### ISSUE TITLE
run in 0.0.0.0 or my public IP

### ISSUE THREAD

**Issue by johnfelipe** [paperai/pdfanno#66]
npm run anno:watch is command for run, but when go to my public IP dont work

**Comment by hshindo** [comment]
Go to `http://localhost:8080/dist/index.html`, not your public IP.

**Comment by johnfelipe** [comment]
"anno:watch": "npm run anno:prepare && webpack-dev-server -d --inline --host 0.0.0.0 --history-api-fallback",

but when put mi publicip:8080/dist/index.html

Invalid Host header


How fix that

**Comment by johnfelipe** [comment]
https://github.com/paperai/pdfanno/issues/66#issuecomment-306687955 i cannt do it, because i have ubuntu 14.04 but server not desktop

**Comment by hshindo** [comment]
Is this related?
https://github.com/webpack/webpack-dev-server/issues/882

**Comment by johnfelipe** [comment]
then what i need to do update

    "webpack": "1.12.14",
    "webpack-dev-server": "^1.14.1",
    "webpack-livereload-plugin": "^0.11.0"

or what is your suggestion?

**Comment by fishmandev** [comment]
> How fix that

Try to add --public arg, where value is "your_ip_or_your_hostname:port"
Example:
`... webpack-dev-server -d --inline --host 0.0.0.0 --public 192.168.0.100:8080 ...`
In browser, go to http://192.168.0.100:8080
