### ISSUE TITLE
Not able to annotate a PDF

### ISSUE THREAD

**Issue by abhinavprk** [paperai/pdfanno#91]
Hi,

I have built and installed the app locally. I am trying to annotate a pdf with pdfAnno running at my localhost. When I select or double click on a span, I don't see any option getting populated to annotate it. 

![image](https://user-images.githubusercontent.com/12445860/29497795-f55dfe32-85ee-11e7-992d-54b06d340839.png)

Please advise. 

Thanks,
Abhinav

**Comment by hshindo** [comment]
Hi,
I can reproduce the problem.
Give us some time to confirm.

**Comment by abhinavprk** [comment]
Thank you 👍

**Comment by abhinavprk** [comment]
Hello,

Is there any update on this issue?

**Comment by hshindo** [comment]
Hi,
We've fixed some related issues.
Could you try it again?

**Comment by hshindo** [comment]
I'm sure this is currently fixed on the master.
Tell us there's still problems.
